// Datos iniciales extraídos del Plan Abierto Sep 2025
// Se cargan al Sheet solo si las hojas están vacías

export const CATEGORIAS = [
  "Vacas cría","Vacas pariendo","Vacas solteras","Vacas TE","Vacas solteras adultas",
  "Vaquillas Cbo 4","Vaquillas Cbo 4 preñadas","Vaquillas Cbo 4 solteras",
  "Desmamantes H","Desmamantes M","Terneros H Cbo6","Terneros M Cbo6",
  "Vacas FIV","Toros Cbo3","Toros Cbo4","Equinos","Otra",
];

export const MOTIVOS = [
  "Planificación","Venta","Muerte","Nacimiento","Destete","Rechazo","Sanidad","Otro",
];

export const POTREROS_INIT = [
  {id:"p01",nombre:"Guayaibí Gualberto",ha:"133",zona:"Guayaibí"},
  {id:"p02",nombre:"Guayaibí Manejo",ha:"75.6",zona:"Guayaibí"},
  {id:"p03",nombre:"A22",ha:"45.2",zona:"Yvytype"},
  {id:"p04",nombre:"Yvytype Natural",ha:"49.8",zona:"Yvytype"},
  {id:"p05",nombre:"Espinillar 5",ha:"32.7",zona:"Espinillar"},
  {id:"p06",nombre:"Ykua María",ha:"156",zona:"Espinillar"},
  {id:"p07",nombre:"Espinillar 1",ha:"28",zona:"Espinillar"},
  {id:"p08",nombre:"Espinillar 2",ha:"34.7",zona:"Espinillar"},
  {id:"p09",nombre:"Espinillar 3",ha:"61",zona:"Espinillar"},
  {id:"p10",nombre:"Espinillar 4",ha:"61.3",zona:"Espinillar"},
  {id:"p11",nombre:"Espinillar 6",ha:"34.2",zona:"Espinillar"},
  {id:"p12",nombre:"Espinillar 7",ha:"36.6",zona:"Espinillar"},
  {id:"p13",nombre:"Espinillar 8",ha:"37",zona:"Espinillar"},
  {id:"p14",nombre:"Jariguaa Fondo 1",ha:"25.5",zona:"Jariguaa"},
  {id:"p15",nombre:"Jariguaa Fondo 2",ha:"30.8",zona:"Jariguaa"},
  {id:"p16",nombre:"Jariguaa 1",ha:"16.7",zona:"Jariguaa"},
  {id:"p17",nombre:"Jariguaa 2",ha:"14.9",zona:"Jariguaa"},
  {id:"p18",nombre:"Jariguaa 3",ha:"11.8",zona:"Jariguaa"},
  {id:"p19",nombre:"Jariguaa 4",ha:"18.6",zona:"Jariguaa"},
  {id:"p20",nombre:"Jariguaa 5",ha:"12.8",zona:"Jariguaa"},
  {id:"p21",nombre:"Jariguaa 6",ha:"13.5",zona:"Jariguaa"},
  {id:"p22",nombre:"Jariguaa 7",ha:"11.7",zona:"Jariguaa"},
  {id:"p23",nombre:"Jariguaa 8",ha:"12",zona:"Jariguaa"},
  {id:"p24",nombre:"Jariguaa 9",ha:"12.1",zona:"Jariguaa"},
  {id:"p25",nombre:"Jariguaa 10",ha:"14.1",zona:"Jariguaa"},
  {id:"p26",nombre:"Jariguaa 11",ha:"11.2",zona:"Jariguaa"},
  {id:"p27",nombre:"Jariguaa 12",ha:"11",zona:"Jariguaa"},
  {id:"p28",nombre:"Guayaibí Agrícola",ha:"75",zona:"Guayaibí"},
  {id:"p29",nombre:"Guayaibí'i",ha:"20.8",zona:"Guayaibí"},
  {id:"p30",nombre:"Agrícola Fondo 1",ha:"23.6",zona:"Agrícola"},
  {id:"p31",nombre:"Agrícola Fondo 2",ha:"23",zona:"Agrícola"},
  {id:"p32",nombre:"Agrícola Fondo 3",ha:"18.47",zona:"Agrícola"},
  {id:"p33",nombre:"Agrícola Fondo 4",ha:"19.6",zona:"Agrícola"},
  {id:"p34",nombre:"F18 Pastura 1",ha:"21",zona:"F18"},
  {id:"p35",nombre:"F18 Pastura 2",ha:"12",zona:"F18"},
  {id:"p36",nombre:"F18 Pastura 3",ha:"19",zona:"F18"},
  {id:"p37",nombre:"F18 Pastura 4",ha:"8",zona:"F18"},
  {id:"p38",nombre:"F19 Pastura 1",ha:"8",zona:"F19"},
  {id:"p39",nombre:"F19 Pastura 2",ha:"17",zona:"F19"},
  {id:"p40",nombre:"F19 Pastura 3",ha:"18",zona:"F19"},
  {id:"p41",nombre:"F20",ha:"35",zona:"F20"},
  {id:"p42",nombre:"Yvytype 1",ha:"10.9",zona:"Yvytype"},
  {id:"p43",nombre:"Yvytype 2",ha:"11.1",zona:"Yvytype"},
  {id:"p44",nombre:"Yvytype 3",ha:"27",zona:"Yvytype"},
  {id:"p45",nombre:"Yvytype 4",ha:"17",zona:"Yvytype"},
  {id:"p46",nombre:"Yvytype 5",ha:"58",zona:"Yvytype"},
  {id:"p47",nombre:"Yvytype 6",ha:"17",zona:"Yvytype"},
  {id:"p48",nombre:"Pastura Retiro 1",ha:"4",zona:"Retiro"},
  {id:"p49",nombre:"Pastura Retiro 2",ha:"4",zona:"Retiro"},
  {id:"p50",nombre:"Pastura Retiro 3",ha:"5",zona:"Retiro"},
  {id:"p51",nombre:"Pastura Retiro 4",ha:"3.9",zona:"Retiro"},
  {id:"p52",nombre:"Pastura Retiro 5",ha:"4",zona:"Retiro"},
  {id:"p53",nombre:"Pastura Retiro 6",ha:"3",zona:"Retiro"},
  {id:"p54",nombre:"Pastura Retiro 7",ha:"2.7",zona:"Retiro"},
  {id:"p55",nombre:"Pastura Retiro 8",ha:"2.8",zona:"Retiro"},
  {id:"p56",nombre:"Pastura Retiro 9",ha:"2.2",zona:"Retiro"},
  {id:"p57",nombre:"Abanico",ha:"70",zona:"Otros"},
  {id:"p58",nombre:"Laurel",ha:"32",zona:"Otros"},
];

export const LOTES_INIT = [
  {id:"L1",nombre:"Lote 1 – Preñadas",color:"#2563eb",
    categorias_json:JSON.stringify([{cat:"Vacas cría",cab:53},{cat:"Vacas pariendo",cab:52}])},
  {id:"L2",nombre:"Lote 2 – Refugos",color:"#7c3aed",
    categorias_json:JSON.stringify([{cat:"Vacas solteras",cab:43},{cat:"Vaquillas Cbo 4",cab:32}])},
  {id:"L3",nombre:"Lote 3 – Vacas Cbo 3 y 4",color:"#059669",
    categorias_json:JSON.stringify([{cat:"Vacas solteras",cab:96},{cat:"Vacas TE",cab:120},{cat:"Vaquillas Cbo 4 solteras",cab:91},{cat:"Vacas solteras adultas",cab:13}])},
  {id:"L4",nombre:"Lote 4 – Vaq Cbo4 PRÑ",color:"#d97706",
    categorias_json:JSON.stringify([{cat:"Vaquillas Cbo 4 preñadas",cab:274}])},
  {id:"L5",nombre:"Lote 5 – Desm Cbo5",color:"#dc2626",
    categorias_json:JSON.stringify([{cat:"Desmamantes H",cab:403}])},
  {id:"L6",nombre:"Lote 6 – Cbo6 Otoñal",color:"#0891b2",
    categorias_json:JSON.stringify([{cat:"Terneros H Cbo6",cab:107},{cat:"Terneros M Cbo6",cab:18}])},
  {id:"L7",nombre:"Lote 7 – Donantes",color:"#6b7280",
    categorias_json:JSON.stringify([{cat:"Vacas FIV",cab:17}])},
  {id:"L8",nombre:"Lote 8 – Toros",color:"#374151",
    categorias_json:JSON.stringify([{cat:"Toros Cbo3",cab:6},{cat:"Toros Cbo4",cab:4}])},
];
